export const DEFAULT_VIDEO_TRACK_VOLUME = 80;
export const DEFAULT_AUDIO_TRACK_VOLUME = 40;

export const KEY_AUDIO_SOURCE = 'as';
export const KEY_AUDIO_VOLUME = 'av';
export const KEY_AUDIO_DELAY = 'ad';
export const KEY_VIDEO_SOURCE = 'vs';
export const KEY_VIDEO_VOLUME = 'vv';
export const KEY_VIDEO_DELAY = 'vd';

export const MUTATION_UPDATE_TRACK_SOURCE = 'UPDATE_TRACK_SOURCE';
export const MUTATION_UPDATE_TRACK_METADATA = 'UPDATE_TRACK_METADATA';
export const MUTATION_UPDATE_TRACK_DELAY = 'UPDATE_TRACK_DELAY';
export const MUTATION_UPDATE_TRACK_VOLUME = 'UPDATE_TRACK_VOLUME';
export const MUTATION_CLEAR_TRACK = 'CLEAR_TRACK';
