export const UPDATE_TRACK_SOURCE = 'UPDATE TRACK SOURCE';
export const UPDATE_TRACK_METADATA = 'UPDATE TRACK METADATA';
export const UPDATE_TRACK_DELAY = 'UPDATE TRACK DELAY';
export const UPDATE_TRACK_VOLUME = 'UPDATE TRACK VOLUME';
export const CLEAR_TRACK = 'CLEAR TRACK';
export const TOGGLE_SHOW_SHARING = 'TOGGLE SHOW SHARING';
export const SET_INVALID_TRACK_SOURCE = 'SET INVALID TRACK SOURCE';
export const CLEAR_INVALID_TRACK_SOURCE = 'CLEAR INVALID TRACK SOURCE';
